
labels:
  - name: '待审核'
    labeled:
      issue:
        body: |
          **您的解封申请已发出**

          我们通常会在5-24h内回复您，请注意查收邮件！

  - name: '需要整改'
    labeled:
      issue:
        body: |
          **⚠️ 抱歉，您的站点仍需进一步整改**

          稍后我们将发邮件告知您需要整改之处，请注意查收邮件！

  - name: '信息不完整'
    labeled:
      issue:
        body: |
          **您好，您所提供的信息不完整**

          请提供您的站点信息以及整改过程！
          
  - name: '审核通过'
    labeled:
      issue:
        body: |
          **🎉 恭喜，您的解封申请已经通过审核**

          您将被移出黑名单，请注意合理使用资源！
